
let content,language='zh';
const route=document.body.dataset.page||'home';
const params=new URLSearchParams(location.search);
language=params.get('lang')==='en'?'en':'zh';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tx=x=>typeof x==='object'&&x!==null?(x[language]||x.zh||''):x;
const t=(zh,en)=>language==='zh'?zh:en;
const link=(p,hash='')=>(p==='home'?'index.html':p+'.html')+(language==='en'?'?lang=en':'')+hash;
const safePath=p=>/^assets\/[a-zA-Z0-9_.-]+$/.test(p||'')?p:'';
const navs=[['home','首页','Home'],['about','关于','About'],['research','研究','Research'],['publications','成果','Publications'],['people','团队与招生','People'],['contact','联系','Contact']];
const doiLink=p=>'https://doi.org/'+encodeURI(p.doi||'').replace(/"/g,'%22');
function pub(p,notes=false){return '<article class="pub-row"><div class="pub-year">'+esc(p.year)+'</div><div><div class="journal">'+esc(p.journal)+' · '+esc(p.details)+'</div><a class="pub-title" target="_blank" rel="noopener" href="'+doiLink(p)+'">'+esc(p.title)+'</a><p class="authors">'+esc(p.authors).replace(/Benteng Wu/g,'<strong>Benteng Wu</strong>')+'</p>'+(notes?'<p class="pub-note">'+esc(tx(p.note))+'</p>':'')+'</div><a class="doi" target="_blank" rel="noopener" href="'+doiLink(p)+'" aria-label="'+esc('DOI: '+p.title)+'">DOI ↗</a></article>'}
function head(eyebrow,title,desc){return '<div class="page-head"><span class="eyebrow">'+eyebrow+'</span><h1>'+title+'</h1>'+(desc?'<p>'+desc+'</p>':'')+'</div>'}
function researchCards(){return content.research.map(r=>'<article class="research-card"><span class="number">'+esc(r.n)+'</span><h3>'+esc(tx(r.title))+'</h3><p>'+esc(tx(r.text))+'</p><a class="text-link" href="'+link('research','#'+r.id)+'">'+t('探索这一方向','Explore this research')+' ↗</a></article>').join('')}
function home(){const p=content.profile;return '<section class="wrap hero"><div><span class="eyebrow">RESOURCE CIRCULARITY & BIOCONVERSION</span><h1>'+esc(tx(p.name))+(language==='zh'?'<span class="english-name">Benteng Wu</span>':'')+'</h1><p class="role">'+esc(tx(p.role))+'</p><p class="institution">'+esc(tx(p.institution))+'</p><p class="intro">'+esc(tx(p.intro))+'</p><div class="actions"><a class="button" href="'+link('research')+'">'+t('了解我的研究','Explore research')+' ↗</a><a class="button secondary" href="'+link('publications')+'">'+t('浏览学术成果','View publications')+'</a></div></div><figure class="portrait-wrap"><img class="portrait" src="'+safePath(p.portrait)+'" alt="'+esc(tx(p.name))+'" width="350" height="400"><figcaption class="portrait-caption">BENTENG WU · '+t('广州，中国','Guangzhou, China')+'</figcaption></figure></section><section class="section pale"><div class="wrap"><div class="section-head"><h2>'+t('研究方向','Research areas')+'</h2><span class="small-note">RESEARCH</span></div><div class="research-grid">'+researchCards()+'</div></div></section><section class="section wrap"><div class="section-head"><h2>'+t('代表性成果','Selected publications')+'</h2><a class="text-link" href="'+link('publications')+'">'+t('更多成果','More publications')+' ↗</a></div>'+content.publications.filter(p=>p.featured).map(p=>pub(p,true)).join('')+'</section>'+join()}
function join(){return content.opportunity.active?'<section class="join-band"><div class="wrap join-inner"><div><h2>'+t('一起探索资源循环的更多可能','Explore resource circularity together')+'</h2><p>'+t('欢迎感兴趣的同学和同行联系，交流研究与合作机会。','Students and fellow researchers are welcome to discuss research interests and collaboration.')+'</p></div><a class="button" href="'+link('people','#opportunities')+'">'+t('团队与招生','People & opportunities')+' ↗</a></div></section>':''}
function about(){return '<div class="wrap content-area">'+head('ABOUT',t('关于吴奔腾','About Benteng Wu'),'')+'<div class="about-layout"><aside class="about-side"><img src="'+safePath(content.profile.portrait)+'" alt="Benteng Wu" width="260" height="347"><div class="actions"><a class="button secondary" href="'+safePath(content.profile.cvZh)+'" target="_blank" rel="noopener">中文简历 ↗</a><a class="button secondary" href="'+safePath(content.profile.cvEn)+'" target="_blank" rel="noopener">English CV ↗</a></div></aside><div><h2>'+t('学术简介','Profile')+'</h2><p>'+esc(tx(content.profile.intro))+'</p><p>'+t('2022 年于爱尔兰科克大学获得环境工程博士学位，随后开展博士后研究。2023 年加入中国科学院广州能源研究所。','I received my PhD in Environmental Engineering from University College Cork in 2022 and continued with postdoctoral research. In 2023, I joined the Guangzhou Institute of Energy Conversion, Chinese Academy of Sciences.')+'</p><h2 style="margin-top:35px">'+t('工作与教育经历','Experience & education')+'</h2><ol class="timeline">'+content.experience.map(e=>'<li><time>'+esc(e.date)+'</time><p>'+esc(e[language])+'</p></li>').join('')+'<p class="small-note" style="margin-top:24px">'+t('项目、学术服务及荣誉详见中英文简历。','For research grants, academic service and awards, please see the CV.')+'</p></div></div></div>'}
function research(){return '<div class="wrap content-area">'+head('RESEARCH',t('研究方向','Research areas'),t('围绕资源循环中的生物转化与材料过程，连接科学问题与应用需求。','Connecting scientific questions with resource recovery through biological conversion and material processes.'))+content.research.map(r=>'<article class="research-detail" id="'+r.id+'"><span class="number">'+esc(r.n)+'</span><div><h2>'+esc(tx(r.title))+'</h2><p class="subtitle">'+esc(tx(r.subtitle))+'</p><p>'+esc(tx(r.text))+'</p><div class="question"><p>'+esc(tx(r.question))+'</p></div><p class="tags">'+esc(tx(r.methods))+'</p><h3>'+t('相关成果','Related publications')+'</h3>'+content.publications.filter(p=>p.topic===r.id).map(p=>'<a class="related text-link" href="'+doiLink(p)+'" target="_blank" rel="noopener">'+esc(p.title)+' ↗</a>').join('')+'</div></article>').join('')+'</div>'}
function publications(){return '<div class="wrap content-area">'+head('PUBLICATIONS',t('学术成果','Publications'),t('完整成果可参见 Google Scholar。','See Google Scholar for the complete publication list.'))+'<div class="actions"><a class="text-link" target="_blank" rel="noopener" href="'+esc(content.profile.scholar)+'">Google Scholar ↗</a></div><div class="filters"><label>'+t('年份','Year')+'<select id="year"><option value="">'+t('全部年份','All years')+'</option>'+[...new Set(content.publications.map(p=>p.year))].sort((a,b)=>b-a).map(y=>'<option>'+y+'</option>').join('')+'</select></label><label>'+t('方向','Area')+'<select id="topic"><option value="">'+t('全部方向','All areas')+'</option>'+content.research.map(r=>'<option value="'+r.id+'">'+esc(tx(r.title))+'</option>').join('')+'</select></label></div><p id="count" class="small-note" aria-live="polite"></p><div id="pub-list"></div></div>'}
function people(){return '<div class="wrap content-area">'+head('PEOPLE & OPPORTUNITIES',t('团队与招生','People & opportunities'),t('以共同的研究兴趣为起点，交流、探索与成长。','A shared interest in research, discovery and learning.'))+[['phd','博士研究生','PhD students'],['master','硕士研究生','Master’s students'],['alumni','毕业成员','Alumni']].map(([id,zh,en])=>'<h2>'+t(zh,en)+'</h2><div class="team-grid">'+content.members.filter(m=>m.status===id).map(m=>'<article class="member"><h3>'+esc(m.name)+'</h3>'+(m.status==='alumni'?'<p class="destination">'+t('毕业去向：','Destination: ')+esc(tx(m.destination)||t('待补充','To be updated'))+'</p>':'')+'</article>').join('')+'</div>').join('')+'<section class="contact-box" id="opportunities"><span class="eyebrow">OPPORTUNITIES</span><h2>'+t('研究交流与招生咨询','Research & student enquiries')+'</h2><p>'+esc(tx(content.opportunity.text))+'</p>'+(content.opportunity.active?'<a class="button" href="mailto:'+esc(content.profile.email)+'">'+t('邮件联系','Get in touch')+' ↗</a>':'<p>'+t('当前未发布招生信息。','No current recruitment announcement.')+'</p>')+'</section></div>'}
function contact(){return '<div class="wrap content-area">'+head('CONTACT',t('联系与交流','Get in touch'),t('欢迎围绕研究合作、学术交流及招生事宜联系。','For research collaborations, academic exchange and student enquiries.'))+'<div class="contact-layout"><div><span class="eyebrow">'+t('工作邮箱','EMAIL')+'</span><a class="contact-email" href="mailto:'+esc(content.profile.email)+'">'+esc(content.profile.email)+'</a><p style="margin-top:24px">'+esc(tx(content.profile.institution))+'<br>'+t('中国 · 广州','Guangzhou, China')+'</p></div><div class="contact-box"><h3>'+t('学术链接与简历','Academic links & CV')+'</h3><div class="contact-links"><a href="'+esc(content.profile.scholar)+'" target="_blank" rel="noopener">Google Scholar ↗</a><a href="'+esc(content.profile.linkedin||"https://www.linkedin.com/in/benteng-wu/")+'" target="_blank" rel="noopener">LinkedIn ↗</a><a href="https://www.giec.cas.cn/" target="_blank" rel="noopener">'+t('广州能源研究所','Guangzhou Institute of Energy Conversion')+' ↗</a><a href="'+safePath(content.profile.cvZh)+'" target="_blank" rel="noopener">中文简历 ↗</a><a href="'+safePath(content.profile.cvEn)+'" target="_blank" rel="noopener">English CV ↗</a></div></div></div></div>'}

let visitorStatsStarted=false,visitorStatsValue=null,visitorStatsState='loading',visitorStatsObserver,visitorStatsTimer;
function renderVisitorStats(){
 const enabled=location.hostname.toLowerCase()==='bentengwu77.github.io'&&!params.has('preview');
 const bar=document.createElement('div');bar.className='wrap site-stats';
 bar.innerHTML='<span>'+t('全站浏览次数（PV）：','Total page views (PV): ')+'</span><span id="busuanzi_container_site_pv" style="display:none"><span id="busuanzi_site_pv"></span></span><span id="visitor-stats-status" role="status"></span><span class="stats-provider"> · <a href="https://www.busuanzi.cc/" target="_blank" rel="noopener" title="'+t('重复浏览会累计计数；由不蒜子提供统计。','Repeat page views are counted. Statistics provided by Busuanzi.')+'">'+t('不蒜子统计','Busuanzi')+' ↗</a></span>';
 document.getElementById('footer').appendChild(bar);
 const value=bar.querySelector('#busuanzi_site_pv'),container=bar.querySelector('#busuanzi_container_site_pv'),status=bar.querySelector('#visitor-stats-status');
 if(visitorStatsObserver)visitorStatsObserver.disconnect();
 if(visitorStatsValue!==null){value.textContent=visitorStatsValue;container.style.display='inline';status.textContent=''}else{status.textContent=!enabled?t('预览不计数','Preview excluded'):visitorStatsState==='unavailable'?t('暂不可用','Unavailable'):t('加载中…','Loading…')}
 if(!enabled)return;
 visitorStatsObserver=new MutationObserver(()=>{const text=value.textContent.trim();if(/^\d+$/.test(text)){visitorStatsValue=text;visitorStatsState='ready';clearTimeout(visitorStatsTimer);visitorStatsObserver.disconnect();container.style.display='inline';status.textContent=''}});
 visitorStatsObserver.observe(value,{childList:true,subtree:true,characterData:true});
 if(visitorStatsStarted)return;
 visitorStatsStarted=true;
 const fail=()=>{if(visitorStatsValue!==null)return;visitorStatsState='unavailable';const message=document.getElementById('visitor-stats-status');if(message)message.textContent=t('暂不可用','Unavailable')};
 const script=document.createElement('script');script.src='https://cdn.busuanzi.cc/busuanzi/3.6.9/busuanzi.min.js';script.async=true;script.onerror=fail;document.head.appendChild(script);
 visitorStatsTimer=setTimeout(fail,8000);
}

function render(){
 document.documentElement.lang=language==='zh'?'zh-CN':'en';
 const current=navs.find(n=>n[0]===route)||navs[0];document.title=(language==='zh'?current[1]:current[2])+' · '+tx(content.profile.name);
 $('#header').innerHTML='<div class="wrap navrow"><a class="brand" href="'+link('home')+'"><span class="monogram">BW</span><span><strong>'+esc(tx(content.profile.name))+'</strong><small>RESEARCH & CIRCULARITY</small></span></a><button class="menu-button" aria-expanded="false" aria-controls="navigation">'+t('菜单','Menu')+'</button><nav class="nav" id="navigation" aria-label="'+t('主导航','Main navigation')+'">'+navs.map(([id,zh,en])=>'<a href="'+link(id)+'" '+(id===route?'aria-current="page"':'')+'>'+t(zh,en)+'</a>').join('')+'</nav><button class="lang" aria-label="'+t('Switch to English','切换为中文')+'">'+t('EN','中文')+'</button></div>';
 $('#main').innerHTML=({home,about,research,publications,people,contact}[route]||home)();
 $('#footer').innerHTML='<div class="wrap footer-inner"><p>© '+new Date().getFullYear()+' Benteng Wu · '+t('个人学术网站','Personal academic website')+'<br>'+t('内容更新：','Updated: ')+esc(content.updated)+'</p><div class="footer-links"><a href="mailto:'+esc(content.profile.email)+'">Email</a><a href="'+esc(content.profile.scholar)+'" target="_blank" rel="noopener">Google Scholar ↗</a></div></div>';
 renderVisitorStats();
 $('.menu-button').onclick=()=>{const open=$('.nav').classList.toggle('open');$('.menu-button').setAttribute('aria-expanded',String(open))};
 $('.lang').onclick=()=>{language=language==='zh'?'en':'zh';history.replaceState(null,'',link(route,location.hash));render()};
 if(route==='publications'){const filter=()=>{const list=content.publications.filter(p=>(!$('#year').value||String(p.year)===$('#year').value)&&(!$('#topic').value||p.topic===$('#topic').value)).sort((a,b)=>b.year-a.year);$('#count').textContent=t('显示 '+list.length+' 篇论文',list.length+' publications');$('#pub-list').innerHTML=list.length?list.map(p=>pub(p,true)).join(''):'<p class="empty">'+t('暂无匹配论文。','No matching publications.')+'</p>'};$('#year').onchange=filter;$('#topic').onchange=filter;filter()}
}
fetch('content.json').then(r=>{if(!r.ok)throw Error('Content unavailable');return r.json()}).then(d=>{content=d;render();if(params.has('preview')){const b=document.createElement('div');b.className='preview-banner';b.textContent='本地编辑预览 / Local draft preview';document.body.prepend(b);if(window.opener)window.opener.postMessage({type:'academic-preview-ready'},location.origin)}}).catch(()=>{$('#main').innerHTML='<div class="wrap section"><h1>暂时无法加载内容</h1><p>请刷新页面重试，或通过 wubt@ms.giec.ac.cn 联系。</p></div>'});
window.addEventListener('message',e=>{if(params.has('preview')&&e.origin===location.origin&&e.source===window.opener&&e.data?.type==='academic-preview-data'){content=e.data.content;render()}});

