
let data,tab='publications',editing=-1,previewWindow,unsavedFiles=false;
const assets=new Map(),$=s=>document.querySelector(s),key='benteng-academic-draft-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tabs=[['publications','论文'],['profile','个人介绍'],['research','研究方向'],['members','团队成员'],['opportunity','招生信息'],['files','简历与照片']];
const status=s=>$('#status').textContent=s;
const field=(name,label,value,type='text',full=false)=>'<label class="'+(full?'full':'')+'">'+label+(type==='textarea'?'<textarea name="'+name+'">'+esc(value)+'</textarea>':'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'">')+'</label>';
function save(){data.updated=new Date().toISOString().slice(0,10);try{localStorage.setItem(key,JSON.stringify(data));status('草稿已保存在当前浏览器。请导出后发布。')}catch{status('浏览器无法保存草稿，请立即导出备份。')}}
function options(selected){return data.research.map(r=>'<option value="'+esc(r.id)+'" '+(r.id===selected?'selected':'')+'>'+esc(r.title.zh)+'</option>').join('')}
function form(inner){return '<form id="edit-form"><div class="form-grid">'+inner+'</div><div class="actions" style="margin-top:24px"><button class="button" type="submit">保存到草稿</button><button id="cancel-edit" class="button secondary" type="button">取消</button></div></form>'}
function render(){
 $('.edit-tabs').innerHTML=tabs.map(([id,title])=>'<button role="tab" aria-selected="'+(tab===id)+'" data-tab="'+id+'">'+title+'</button>').join('');
 let out='';
 if(tab==='publications'){
 out='<h2>论文管理</h2><p class="small-note">新增论文后可选择首页展示。请使用正式发表的作者顺序和 DOI。</p><div class="edit-list">'+data.publications.map((p,i)=>'<div class="edit-item"><span>'+esc(p.year)+' · '+esc(p.title)+(p.featured?' · 首页代表作':'')+'</span><div class="actions"><button class="button secondary" data-edit="'+i+'">编辑</button><button class="danger" data-delete="'+i+'">删除</button></div></div>').join('')+'</div>';
 const p=editing>=0?data.publications[editing]:{year:new Date().getFullYear(),note:{},featured:false};
 out+='<h3>'+(editing>=0?'编辑论文':'新增论文')+'</h3>'+form(field('title','完整题名 *',p.title,'text',true)+field('authors','作者列表 *',p.authors,'text',true)+field('journal','期刊 *',p.journal)+field('details','卷期 / 页码 / 文章号',p.details)+field('year','发表年份 *',p.year,'number')+field('doi','DOI *（可粘贴 DOI 链接）',p.doi)+'<label>研究方向<select name="topic">'+options(p.topic)+'</select></label><label>首页展示<select name="featured"><option value="false" '+(!p.featured?'selected':'')+'>否</option><option value="true" '+(p.featured?'selected':'')+'>是</option></select></label>'+field('noteZh','中文贡献说明',p.note?.zh,'textarea')+field('noteEn','英文贡献说明',p.note?.en,'textarea'));
 }else if(tab==='profile'){
 const p=data.profile;out='<h2>个人介绍</h2>'+form(field('nameZh','中文姓名',p.name.zh)+field('nameEn','英文姓名',p.name.en)+field('roleZh','中文职称',p.role.zh)+field('roleEn','英文职称',p.role.en)+field('institutionZh','中文机构',p.institution.zh)+field('institutionEn','英文机构',p.institution.en)+field('email','工作邮箱',p.email,'email')+field('scholar','Google Scholar 链接',p.scholar,'url')+field('linkedin','LinkedIn 链接',p.linkedin||'https://www.linkedin.com/in/benteng-wu/','url')+field('introZh','中文简介',p.intro.zh,'textarea')+field('introEn','英文简介',p.intro.en,'textarea'));
 }else if(tab==='research'){
 const r=data.research[editing<0?0:editing];out='<h2>研究方向</h2><div class="actions" style="margin-bottom:25px">'+data.research.map((r,i)=>'<button class="button secondary" data-edit="'+i+'">'+esc(r.title.zh)+'</button>').join('')+'</div>'+form(field('titleZh','中文名称',r.title.zh)+field('titleEn','英文名称',r.title.en)+field('subtitleZh','中文副标题',r.subtitle.zh)+field('subtitleEn','英文副标题',r.subtitle.en)+field('textZh','中文介绍',r.text.zh,'textarea')+field('textEn','英文介绍',r.text.en,'textarea')+field('questionZh','中文科学问题',r.question.zh,'textarea')+field('questionEn','英文科学问题',r.question.en,'textarea')+field('methodsZh','中文方法概览',r.methods.zh)+field('methodsEn','英文方法概览',r.methods.en));
 }else if(tab==='members'){
 out='<h2>团队成员</h2><div class="edit-list">'+data.members.map((m,i)=>'<div class="edit-item"><span>'+esc(m.name)+' · '+esc(m.year)+' · '+({phd:'博士生',master:'硕士生',alumni:'毕业成员'})[m.status]+'</span><div class="actions"><button class="button secondary" data-edit="'+i+'">编辑</button><button class="danger" data-delete="'+i+'">删除</button></div></div>').join('')+'</div>';
 const m=editing>=0?data.members[editing]:{};out+='<h3>'+(editing>=0?'编辑成员':'新增成员')+'</h3>'+form(field('name','姓名 *',m.name)+field('year','所列年份',m.year)+field('destinationZh','毕业去向（中文）',m.destination?.zh)+field('destinationEn','毕业去向（英文）',m.destination?.en)+'<label>成员状态<select name="status">'+[['phd','博士生'],['master','硕士生'],['alumni','毕业成员']].map(([id,name])=>'<option value="'+id+'" '+(m.status===id?'selected':'')+'>'+name+'</option>').join('')+'</select></label>');
 }else if(tab==='opportunity'){
 out='<h2>招生信息</h2>'+form('<label>信息状态<select name="active"><option value="true" '+(data.opportunity.active?'selected':'')+'>开放联系</option><option value="false" '+(!data.opportunity.active?'selected':'')+'>关闭</option></select></label>'+field('textZh','中文说明',data.opportunity.text.zh,'textarea',true)+field('textEn','英文说明',data.opportunity.text.en,'textarea',true));
 }else{
 out='<h2>简历与照片</h2><p>选择新文件后，导出完整网站即可包含替换后的版本。上传的文件仅保留在本次页面会话中；请先导出，再关闭页面。</p><div class="form-grid">'+[['cvZh','中文简历 PDF','.pdf,application/pdf'],['cvEn','英文简历 PDF','.pdf,application/pdf'],['portrait','个人照片 JPEG / PNG','image/jpeg,image/png']].map(([id,title,accept])=>'<label>'+title+'<input type="file" data-asset="'+id+'" accept="'+accept+'"><span class="small-note">'+(assets.has(data.profile[id])?'已选择替换文件':'当前：'+esc(data.profile[id]))+'</span></label>').join('')+'</div>';
 }
 $('#edit-panel').innerHTML=out;
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;editing=-1;render()});
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=Number(b.dataset.edit);render();$('#edit-form')?.scrollIntoView({block:'center'})});
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('从草稿中删除这一条？线上内容不会立即变化。')){data[tab].splice(Number(b.dataset.delete),1);editing=-1;save();render()}});
 if($('#cancel-edit'))$('#cancel-edit').onclick=()=>{editing=-1;render()};
 if($('#edit-form'))$('#edit-form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const pair=(a)=>({zh:f[a+'Zh'].trim(),en:f[a+'En'].trim()});
 if(tab==='publications'){const doi=f.doi.trim().replace(/^https?:\/\/(dx\.)?doi\.org\//i,'');if(!f.title.trim()||!f.authors.trim()||!f.journal.trim()||!/^10\.\d{4,9}\/\S+$/.test(doi)||Number(f.year)<1900||Number(f.year)>2100)return status('请填写题名、作者、期刊、有效年份与 DOI。');if(data.publications.some((p,i)=>i!==editing&&p.doi.toLowerCase()===doi.toLowerCase()))return status('该 DOI 已存在，请编辑原论文，避免重复。');
 const p={id:editing>=0?data.publications[editing].id:'p'+Date.now(),year:Number(f.year),title:f.title.trim(),authors:f.authors.trim(),journal:f.journal.trim(),details:f.details.trim(),doi,topic:f.topic,featured:f.featured==='true',note:pair('note')};if(editing>=0)data.publications[editing]=p;else data.publications.push(p);
 }else if(tab==='profile'){let u;try{u=new URL(f.scholar)}catch{return status('请输入有效的学术主页网址。')}if(f.linkedin&&!['https://www.linkedin.com/','https://linkedin.com/'].some(prefix=>f.linkedin.startsWith(prefix)))return status('请输入有效的 LinkedIn HTTPS 链接。');if(u.protocol!=='https:')return status('学术主页应使用 HTTPS 链接。');Object.assign(data.profile,{name:pair('name'),role:pair('role'),institution:pair('institution'),intro:pair('intro'),email:f.email.trim(),scholar:u.href,linkedin:f.linkedin.trim()});
 }else if(tab==='research'){const r=data.research[editing<0?0:editing];for(const k of ['title','subtitle','text','question','methods'])r[k]=pair(k);
 }else if(tab==='members'){if(!f.name.trim())return status('请填写成员姓名。');const m={name:f.name.trim(),year:f.year.trim(),status:f.status,destination:pair('destination')};if(editing>=0)data.members[editing]=m;else data.members.push(m);
 }else if(tab==='opportunity'){data.opportunity={active:f.active==='true',text:pair('text')}}save();editing=-1;render()};
 document.querySelectorAll('[data-asset]').forEach(input=>input.onchange=async()=>{const file=input.files[0];if(!file)return;const id=input.dataset.asset;if(file.size>20*1024*1024)return status('文件请控制在 20 MB 以内。');if(id!=='portrait'&&file.type!=='application/pdf')return status('请上传 PDF 文件。');if(id==='portrait'&&!['image/jpeg','image/png'].includes(file.type))return status('请上传 JPEG 或 PNG 图片。');const path=id==='portrait'?'assets/portrait.'+(file.type==='image/png'?'png':'jpg'):'assets/'+(id==='cvZh'?'cv-zh.pdf':'cv-en.pdf');data.profile[id]=path;assets.set(path,new Uint8Array(await file.arrayBuffer()));unsavedFiles=true;status('文件已选择，请导出完整网站以保存替换文件。');render()});
}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function validate(d){if(!d||!d.profile||!Array.isArray(d.research)||!d.research.length||!Array.isArray(d.publications)||!Array.isArray(d.members)||!d.opportunity||!Array.isArray(d.experience))throw Error('备份结构不完整');for(const k of ['name','role','institution','intro'])if(typeof d.profile[k]?.zh!=='string'||typeof d.profile[k]?.en!=='string')throw Error('个人介绍格式不正确');if(!/^https:\/\//.test(d.profile.scholar)||!/^\S+@\S+\.\S+$/.test(d.profile.email))throw Error('联系链接格式不正确');for(const k of ['portrait','cvZh','cvEn'])if(!/^assets\/[a-zA-Z0-9_.-]+$/.test(d.profile[k]))throw Error('文件路径不正确');for(const r of d.research){if(!/^[a-zA-Z0-9-]+$/.test(r.id))throw Error('研究方向标识不正确');for(const k of ['title','subtitle','text','question','methods'])if(typeof r[k]?.zh!=='string'||typeof r[k]?.en!=='string')throw Error('研究方向格式不完整')}for(const p of d.publications)if(!p.title||!p.authors||!p.journal||!/^10\.\d{4,9}\/\S+$/.test(p.doi)||!Number.isInteger(p.year)||!d.research.some(r=>r.id===p.topic))throw Error('论文格式不正确');if(d.profile.linkedin&&!['https://www.linkedin.com/','https://linkedin.com/'].some(prefix=>d.profile.linkedin.startsWith(prefix)))throw Error('LinkedIn 链接不正确');for(const m of d.members)if(typeof m.name!=='string'||!['phd','master','alumni'].includes(m.status))throw Error('成员格式不正确');return d}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
function zip(files){const enc=new TextEncoder(),parts=[],central=[];let offset=0,size=0;for(const [name,bytes]of files){const n=enc.encode(name),crc=crc32(bytes),h=new Uint8Array(30+n.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,n.length,true);h.set(n,30);parts.push(h,bytes);const c=new Uint8Array(46+n.length),cv=new DataView(c.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,crc,true);cv.setUint32(20,bytes.length,true);cv.setUint32(24,bytes.length,true);cv.setUint16(28,n.length,true);cv.setUint32(42,offset,true);c.set(n,46);central.push(c);size+=c.length;offset+=h.length+bytes.length}const end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,files.length,true);ev.setUint16(10,files.length,true);ev.setUint32(12,size,true);ev.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/zip'})}
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===previewWindow&&e.data?.type==='academic-preview-ready')previewWindow.postMessage({type:'academic-preview-data',content:data},location.origin)});
window.addEventListener('beforeunload',e=>{if(unsavedFiles){e.preventDefault();e.returnValue=''}});
async function init(){try{const r=await fetch('content.json');if(!r.ok)throw Error('网页内容读取失败');data=await r.json();let draft;try{draft=localStorage.getItem(key)}catch{}if(draft){try{data=validate(JSON.parse(draft));status('已恢复当前浏览器的编辑草稿。')}catch{status('旧草稿无法读取，已载入线上内容。')}}render();
 $('#preview').onclick=()=>{previewWindow=window.open('index.html?preview=1','academic-draft');if(!previewWindow)status('浏览器阻止了预览窗口，请允许弹出窗口后重试。')};
 $('#export-json').onclick=()=>download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'content.json');
 $('#import-json').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5e6)throw Error('内容备份文件过大');const next=validate(JSON.parse((await f.text()).replace(/^\uFEFF/,'')));if(confirm('用导入内容替换当前草稿？')){data=next;editing=-1;save();render()}}catch(err){status('导入失败：'+err.message)}e.target.value=''};
 $('#export-site').onclick=async()=>{const b=$('#export-site');b.disabled=true;status('正在收集页面、图片与简历…');try{const paths=['index.html','about.html','research.html','publications.html','people.html','contact.html','editor.html','app.js','editor.js','style.css','使用说明.txt',data.profile.portrait,data.profile.cvZh,data.profile.cvEn];const files=[];for(const p of [...new Set(paths)]){if(assets.has(p)){files.push([p,assets.get(p)]);continue}const r=await fetch(p);if(!r.ok)throw Error('无法读取 '+p);let bytes=new Uint8Array(await r.arrayBuffer());if(p.endsWith('.html')&&p!=='editor.html'){let html=new TextDecoder().decode(bytes);html=html.replace(/<header id="header"[\s\S]*?<\/header>/,'<header id="header" class="header"></header>').replace(/<main id="main">[\s\S]*?<\/main>/,'<main id="main"><p style="padding:40px">正在载入最新内容…</p></main>').replace(/<footer id="footer"[\s\S]*?<\/footer>/,'<footer id="footer" class="footer"></footer>');bytes=new TextEncoder().encode(html)}files.push([p,bytes])}files.push(['content.json',new TextEncoder().encode(JSON.stringify(data,null,2))]);download(zip(files),'benteng-wu-website-'+data.updated+'.zip');unsavedFiles=false;save();status('完整网站已导出。解压后将其中全部文件发布到您的静态网站空间。')}catch(err){status('导出失败：'+err.message)}finally{b.disabled=false}};
 }catch(err){status('载入失败：'+err.message)}}
init();

